name: 'Actions Readme Feed'
description: 'Display RSS feed in your GitHub Profile README'
author: Sarisia

inputs:
  url:
    description: 'RSS Feed URL'
    required: true
  file:
    description: 'Path to Markdown file to update'
    required: true
  sort:
    description: 'Sort feed entries by date in decending order'
    required: false
    default: 'true'
  max_entry:
    description: 'Number of entries to show'
    required: false
    default: '5'
  format:
    description: 'Feed format string'
    required: false
    default: '- ${monthshort} ${02day} - [${title}](${url})'
  start_flag:
    description: 'Start of feed block in Markdown'
    required: false
    default: '<!-- feed start -->'
  end_flag:
    description: 'End of feed block in Markdown'
    required: false
    default: '<!-- feed end -->'

outputs:
  changed:
    description: Whether the document is changed while this actions's run
  items:
    description: Raw feed entry from rssparser
  newlines:
    description: New lines inserted to the document
  result:
    description: Result document with feed lines inserted

runs:
  using: 'node12'
  main: 'lib/index.js'

branding:
  color: 'red'
  icon: 'rss'
